# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "051130"

#write html inside the double quotes to display in jumbotron
description: "<img style=\"width: 100%;height: 100%;\" src=\"https://img1.imgtp.com/2022/09/24/1he4tloT.png\" title=\"Profile\" />"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://x051130x.github.io" # the base hostname & protocol for your site
github_username: x051130x
