# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "051130"

#write html inside the double quotes to display in jumbotron
description: "<img style=\"width: 100%;height: 100%;\" src=\"https://x051130x.github.io/img/top.png\" title=\"top\" /><h5>GSHA 幻想乡管制区 白玉楼进近席位</h5><h3>051130 here.</h3><h4>是某不知名车车人的博客页捏</h4>"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://x051130x.github.io" # the base hostname & protocol for your site
github_username: x051130x
