# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "051130"

#write html inside the double quotes to display in jumbotron
description: "<img style=\"width: 100%;height: 100%;\" src=\"https://x051130x.github.io/img/top.png\" title=\"top\" /><img style=\"width: 100%;height: 100%;\" src=\"https://x051130x.github.io/img/profile.png\" title=\"profile\" /><img style=\"width: 100%;height: 100%;\" src=\"https://x051130x.github.io/img/ZVOS[B%7BW0R~2[8XOJB7A1F2.jpg\" title=\"touhoubar\" /><img style=\"width: 100%;height: 100%;\" src=\"https://osu-sig.vercel.app/card?user=051130&mode=std&animation=true&hue=200\" title=\"osuprofile\" /><h3>051130 here.</h3><h3>常用id：</h3><h4>THYuyuko_051130(mcjava)</br>051130(其他)</br>墨染の桜 | 051130(qq)</h4><h4>称呼:051，在某些(车万)社群中也可称uuz</h4</br><h4>正在运营的服务器：Space Creator EX(详见页面顶端服务器页)</h4><h3>成分自查：</h3><h4>车万：uuz厨（推千年组）</br>mc：modded，主修create</br>音游：osu！std 6 Digit</br>航空：一般路过飞友，4 ENG JET吹（340/380）</br></br><h4>↓↓↓ 服务器官网的部分页面，以及一些随便写的东西 ↓↓↓</h4>"

https://osu-sig.vercel.app/card?user=051130&mode=std&animation=true&hue=200

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://x051130x.github.io" # the base hostname & protocol for your site
github_username: x051130x
